### PR TITLE
render caret the correct size and at correct location.

### PR DESCRIPTION
**Pull request by danwalmsley**
This raises the question:

Do you know what HeightFactor and BaselineFactor are?

### CODE REVIEW

**Comment by aelij** [comment]
> Do you know what HeightFactor and BaselineFactor are?
These are approximations I made since there's no text metrics API in Avalonia. They are actually derived from each typeface (font family).

I'm not sure multiplying by these factors is the right fix. `CalculateDefaultTextMetrics` should have produced the correct results. These constants should not be used outside of the `TextLine` implementation.

**Comment by aelij** [comment]
Baseline

**Comment by aelij** [comment]
Hmm, seems like there's a major difference between WPF's text rendering and Avalonia's. WPF's `DrawingContext` draws glyph runs using the Baseline as the Y coordinate, while Avalonia uses the top-left coordinate. Perhaps all of these baseline calculations aren't needed at all.

**Comment by danwalmsley** [comment]
@aelij I'm pretty sure formatted text class takes care of this for us but might be wrong.

**Comment by danwalmsley** [comment]
Lets resolve if we need the factors in another pr.

**Comment by aelij** [comment]
It doesn't. Imagine you have a text line with all sorts of fonts. `FormattedText` could represent a single text run within that line. Different fonts have different baselines (and line heights) so they need to be aligned. And that's what `TextLine` essentially does - it creates runs and aligns them in a line.

While this is not a concern for AvaloniaEdit (since it only allows a single font), if in the future we'd like to have a rich text box in Avalonia the `TextLine` implementation here could potentially be used.

For the time being, I'm going to close this PR and resolve this in another way (already have an idea how).

**Pull request closed without merging**
